# Generated by Django 3.2.10 on 2021-12-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_was_published_recently'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='was_published_recenetly',
        ),
        migrations.RemoveField(
            model_name='question',
            name='was_published_recently',
        ),
    ]
